### ISSUE TITLE
Calculator unresponsive for any of the ML models

### ISSUE THREAD

**Issue by shikhar-srivastava** [luxedo/calcuMLator#1]

**Comment by shikhar-srivastava** [comment]
![capture](https://cloud.githubusercontent.com/assets/12572543/19222323/7459479c-8e73-11e6-9a2f-f0e3877d3bc3.JPG)

None of the models are being loaded and executed for the calculation, on pressing  '='.

**Comment by luxedo** [comment]
Can you provide some info on your system?
Do you have the dependencies installed? `python` and `scikit-learn`
I'll take a look and try to package it better.

**Comment by shikhar-srivastava** [comment]
Sure, Here's a little information:
Intel Core i5 4210U, 4 GB DDR3 RAM, running Windows 8.1 x64. 
All required dependencies including sklearn 0.17, python, are installed.

**Comment by luxedo** [comment]
Yeah, I didn't worked with windows.
I'm trying to host this at [heroku](https://elements.heroku.com/buildpacks/projetoeureka/heroku-buildpack-python-sklearn), then you can just run it in the browser.

**Comment by luxedo** [comment]
Hey man! I removed the electon app and managed to set it up at heroku.
Check it out [here](http://armlessjohn404.github.io/calcuMLator/)
